### ISSUE TITLE
MediaPlayerElement control with seekbar mouse hover thumbnails

### ISSUE THREAD

**Issue by touseefbsb** [lukasf/FFmpegInterop#24] opened 2018-03-09 14:09 UTC
Ok guyx as you have created this fork to speed up the improvement of ffmpeg interop in uwp. I really appreciate it. I am not so good with ffmpeg stuff, but I do have lot of experience in uwp stuff. So I want to help by giving you guyx some ideas and possibly help to add some more features.
@lukasf  @mcosmin222 
So here is a feature I recently requested on uwp community toolkit. 
https://github.com/Microsoft/UWPCommunityToolkit/issues/1840
I suppose ffmpeginterop can help us extract frames on specific positions? If that is the case then I think this feature is do able with MediaPlayerElement right? let me know what you guyx think about it and would u guyx be interesting in moving forward with this feature in this fork? The details of the feature is in the link I provided above.

**Comment by lukasf** [comment] 2018-03-09 19:50
I have recently thought about this as well, after I saw it in MPC-BE. Not sure if it is really a useful feature, but it's kind of cool anyways. It is already possible to extract frames with FFmpegInterop. If you use "exactSeek=false", this is also surprisingly fast. But the current solution only grabs one frame and then closes the file. Repeatedly opening and closing the file will not be very efficient. If you want such a live seek preview, we'd need a different approach. Like a dedicated FFmpegFrameGrabber class, which opens the file and leaves it open, and lets you grab frames at random positions.

But then you also need the control to show the images. This probably won't be added to UWPCommunityToolkit, because there is no good way to create such images in UWP - and they won't create a dependency to FFmpegInterop...

**Comment by touseefbsb** [comment] 2018-03-09 19:55
we can show the thumbnails in the ui, in the flyout of the slider ( seekbar ) I think there is already a flyout on the slider with name "Thumbnail" in it. the main question then arises, that when the mouse is on the slider, how do we know which exact position is the mouse on? so we can convert that exact position to the timeline of the video and then extract the thumbnail on that exact position, and show it to the flyout.

**Comment by touseefbsb** [comment] 2018-03-09 19:57
is there a way we can get the thumbnails in the stream? like all other things, like subtitles and audio streams? so if we can get a stream of thumbnails as well in the same pipeline , maybe with a boolean so developer can turn off the feature if they dont want it at all? and then mouseEntered and mouseExited events can be handled in the slider to show the thumbnails. Just a rough idea though, not really sure whether thumbnails can come through the stream source

**Comment by lukasf** [comment] 2018-03-09 20:23
I am not sure what you mean. You don't want thumbnails of the position you are playing, you want them for random positions where the mouse is over. So nope, this cannot be added to the normal playback stream in any way. It must be done with a separate ffmpeg instance, which is able to seek to very different parts of the file and grab frames from there. You can't open different parts of the stream at the same time with only one ffmpeg instance.

**Comment by lukasf** [comment] 2018-03-09 20:28
I thoght that the "Thumbnail" property was there to show a preview image before the actual image/video is available. But I could be wrong. If you find out more, please let us know. But my feeling is that we'd need to create a custom control to achieve what we want. 

I also do not like the default transport controls. Especially the seek bar is done horribly. When you click on a location, the slider always jumps to a slightly different position, sometimes forward, sometimes backward, but never exactly where you click. I don't know what the hell it is doing, but it is doing really bad. It is not because we seek to imprecise positions, it is a bug in the control.

**Comment by touseefbsb** [comment] 2018-03-09 21:11
yeah obviously we will need a custom control, a custom MediaTransportControl can do that job, and we can override whatever the default behaviour of that thumbnail flyout is. I havent noticed the bug you are refering to, I think the only problem in default controls is the big round thumb which is used to move the slider, but its style can be easily changed to a smaller and more easy to use thumb.

**Comment by touseefbsb** [comment] 2018-03-09 21:13
ok so we can use a different class for grabbing the random thumbnail acording to position and we can use the pointer enterd and exited events on the custom control and supply those images to the flyout of the slider. we dont need to create a control from scratch, we just need to create a custom Media Transport Controls. i.e: just desirve from the default Media Transport controls, change the style a little as per requirements, and handle the events and backend code in that custom control, or even that functionality can be exposed with dependency properties and events.

**Comment by touseefbsb** [comment] 2018-03-09 21:15
the core part still is to create that frame grabber class and how to use that to get images? supplying those images wont be so complicated and a custom derived Media Transport Control will probably do the job.

**Comment by mcosmin222** [comment] 2018-03-10 14:04
In my app, I implemented this the following way: grab 40 frames equally spread in the stream, and display them in a GridView. Then the user can click on a frame and seek to the exact location of said frame. It is not perfect, because it gives you only specific, predetermined points in the stream to seek. But this is what others do to. They do not just grab the frame at mouse over, they have fixed positions in the stream at which they preload a frame and serve that up instead, using the seekbar and not a grid view. When you click on the bar, it seeks to the actual location and not at the thumbnail.

The way I see it, the frame grabber will simply reuse the FFMPEG interop object. We can create an overload to the existing frame grabber methods which recieve a FFMPEG interop object fully initialized to use to get the frames.

**Comment by touseefbsb** [comment] 2018-03-10 15:22
@mcosmin222  I think wht u have implemented in ur app is a bit different feature, sort of like chapters/milestones which can help user seek to a specific scene with help of the thumbnail. but this feature requires mouse hover stuff. the logic can be somewhat same in terms of grabbing the frames as u suggested, but not 40, but I think it will be around 100, and depending on resize of the window will that effect this scenario?

**Comment by touseefbsb** [comment] 2018-03-10 15:25
@mcosmin222  can I know the name of ur app? so I can look at it for inspiration purpose? :)

**Comment by mcosmin222** [comment] 2018-03-10 16:35
You can grab a frame once every minute or something. The point is, the frames are preloaded. And the hover just displays them in them in a popup. That is just UI logic.

I know my idea is different but the logic behind it is roughly the same.

**Comment by touseefbsb** [comment] 2018-03-10 17:02
@mcosmin222  Do we have an api within ffmpeg already? to grab the frames?

**Comment by touseefbsb** [comment] 2018-03-10 17:04
how can we divide the slider into the segments? in other words how will we know at which position of the slider, does the user hovers the pointer? with gridview it is easier and straight forward, but with slider we need to know the position of the pointer so we can show up the thumbnail according to the position.

**Comment by mcosmin222** [comment] 2018-03-10 21:33
The slider position thingy is technically not the problem of ffmpeg interop.
Yes, we do have the frame grabber already implemented, we just need to optimize it.

**Comment by lukasf** [comment] 2018-03-12 19:03
I don't think it will be a problem to live decode the frames. MPC-BE does it live and performance is fine. Usually people will just play a video, not seek around, and then it would be a waste to decode 100 frames on startup. Decoding 1 frame is fast, but decoding 50 or 100 is quite some work. So I'd rather retrieve frames only on-demand, and maybe cache them to display faster on further seeking.

But as @mcosmin222 aleady noted, the question of how/when frames are decoded and cached is a thing of the app/UI, it does not really have to do with FFmpegInterop. In this lib we only need a way to retrieve multiple frames from a file, without opening/closing it each time.

**Comment by touseefbsb** [comment] 2018-03-12 19:24
ahan fair enough. if we have optimized way to extract out frames, then we can decide on how to deal with the ui.

**Comment by mcosmin222** [comment] 2018-03-13 15:27
Exactly. And this is a good way of jump starting ffmpeg interop.

**Comment by mcosmin222** [comment] 2018-03-13 18:59
@lukasf , do you think it is still necessary to keep the old "ExtractVideoFrameAsync" methods? 

I think the approach for this would be to have a method "CreateFrameGrabberFromStreamAsync" or something like this, which takes a IRandomAccessStream. The method creates internally the FFMPEG interop object with the config properly set to the intended purpose, and said interop object can then be reused to grab frames at will.

And when calling "GetMediaStreamSource" method, it should throw an exception when the config is set to frame grabber.

**Comment by mcosmin222** [comment] 2018-03-13 19:48
The challenge is still on the UI side. Even if getting a single frame is reasonably fast, I still don't think it will be fast enough to respond to "mouse over" events, I find this will be pretty painful for the Ui to handle properly, and even though it looks like other apps are doing it in real time, I still think there is some caching happening.

**Comment by lukasf** [comment] 2018-03-13 20:01
Regarding your PR, I think it would be better to add a separate FrameGrabber class. If you add this to the normal FFmpegInterop, you'd have a lot of methods on your "FrameGrabber" which are not fully functional and are not needed at all for grabbing frames. And on the other side, if you create a normal FFmpegInterop, you would have "Grab Frame" methods with won't work. So two potential sources of confusion for lib users.

I'd propose to just create a new simple class, which internally creates FFmpegInterop and uses it to grab the frames. Then we have a clean interface on the frame grabber, and a clean FFmpegInterop without public methods that won't work as expected. I'd also like to add a "seek to (binary) file position" method on the frame grabber, this would be easier to use for thumbnail creation and would even work with broken files (e.g. wrong duration).

**Comment by lukasf** [comment] 2018-03-13 20:06
On the UI side you will definitely need some kind of throttling, you cannot react on every pointer event. Like e.g. only grab frames when the cursor has rested for like 100ms, only grab one frame every 0.5s or whatever. When the cursor is moved, you move the preview image seamlessly, but you only update the image content at a slower rate. And as I said, I also think it would be a good idea to cache images once they were decoded, and show cached images whenever possible.

**Comment by mcosmin222** [comment] 2018-03-13 20:11
@lukasf , OK, give me some time to add the new class, and then you can play with the binary seek 👍

**Comment by touseefbsb** [comment] 2018-03-13 22:24
yes having a seperate class makes sense because not every user will want to use this specific feature.

**Comment by mcosmin222** [comment] 2018-03-14 09:06
I added the new class.

**Comment by touseefbsb** [comment] 2018-03-14 09:46
@mcosmin222  the sample already shows how to use this library to play files. this frame grabbing feature, this should also be shown in the sample as a seperate feature so that developers can easily know how to use this class , what do you think?

**Comment by lukasf** [comment] 2018-03-14 09:59
Cool, looks good! I will add file seek stuff in there later today.

@touseefbsb The sample already contains frame grabber code, but it needs to be updated to use the new FrameGrabber class.

**Comment by touseefbsb** [comment] 2018-03-14 10:05
@lukasf  perfect.

**Comment by mcosmin222** [comment] 2018-03-14 11:27
The API is pretty obvious for anyone who's seen a factory method before.

**Comment by lukasf** [comment] 2018-03-14 17:28
I've updated the samples and added binary seek for frame grabber.

**Comment by touseefbsb** [comment] 2018-03-14 17:38
@lukasf  binary seek? what is that?

**Comment by lukasf** [comment] 2018-03-14 17:41
Seeking to a binary position in the file, instead of a timestamp position. This is faster and usually works even with broken files where timestamps are corrupt. But since you do not know which time in the file you will get, it is only useful for thumbnail retrieval, not for seek preview.

**Comment by touseefbsb** [comment] 2018-03-14 17:44
how many thumbnails can we get with this method? I mean can we get multiple thumbnails, on basis of percentages? for example thumbnail at 10 percent of the file, then 20 percent and so on? if we can do that we can roughly convert that to the timestamp position manually in the app

**Comment by mcosmin222** [comment] 2018-03-14 18:39
You can get as many as you want, there are hardware constraints that will limit you. If you look at youtube videos for example, they serve up a seek preview every 3-4 seconds. I am wondering if these async methods should support cancellation, it will probably make them easier to consume from the UI.

I'd do some cancelation checks before each major operation: i.e before read, before convert.

**Comment by touseefbsb** [comment] 2018-03-14 18:42
yeah if we can get a thumbnail roughly after every 5 seconds, maybe not following timestamp but I am sure even with binary seek there will be a way to get a thumbnail after every specific binary data, which will achieve the same result.

**Comment by mcosmin222** [comment] 2018-03-14 18:47
You are confusing the seek preview with thumbnails ^^.

Seek previews are supposed to be accurate, so you have a pretty good guess where you seek, the thumbnail is just some random frame grabbed from the stream. There is already a thumbnail API, which returns the "thumbnail" metadata info, but some files do not have these, so you'd use the binary seek to quickly get a snapshot from the stream and hope for the best.

I suppose you could use the binary seek for seek previews as well.

**Comment by touseefbsb** [comment] 2018-03-14 18:51
@mcosmin222  yes that i wht I am actually thinking of doing, so I am trying to understand how exactly the binary seek works so I can use it for seek preview. by thumbnail I meant the image we will get from binary seek from a specific location of the file. by random do u mean we wont know from which part of the file we r getting that image? ( using binary seek) because in order to use it in seek preview, we need a rough idea of the location/position of tht specific image.

**Comment by touseefbsb** [comment] 2018-03-14 18:59
for example if I somehow divide the slider into equal 100 parts. maybe overlap it with a transparent grid with 100 equal columns, or something like that. so if the user hovers on the 47th column. so I will be needing a frame using binary seek from the stream, and tht frame should come from approximately 47 percent of the video is played. this is just a rough idea in my mind to implement the seek preview. is this possible with frame grabber class? but it wont work as good if the video length is too long so number of columns should be decided based on the length of video, like after every 5 secs.  but actually my main question here is that :  "we r not grabing the frames on basis of timestamp, but is there a way to grab the frame with binary seek on basis of known time? for example if I want a frame at exact 20 seconds of the video, can I do that with binary seek?

**Comment by touseefbsb** [comment] 2018-03-14 19:21
a while ago I aked this question on stackoverflow, here is the link
https://stackoverflow.com/questions/44598082/uwp-media-element-seekbar-pointer-hover-frame-show
 according to the answer I got, I understand there is no api for **hovering** but we do have an event known as **ThumbnailRequested** on the default controls which can be used with the args to set the thumbnail image using the method **SetThumbnailImage(IInputStream)
** this event is raised when the user seeks the video, so do we get the image according to the seek position? and secondly I dont understand where is this parameter **InputStream** coming from which we need to provide to the setThumbnailImage method?

**Comment by mcosmin222** [comment] 2018-03-14 19:40
This is a rather custom use case, I do not believe they will add it into the SDK. Learning the value at which the pointer hovers is rather complicated, but do-able. You can use Pointer events, which expose this property

https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.pointerpoint

You can determine the position of the pointer, and knowing the length of the slider, you can give a good approximation on the value of the hover-over event.

You then just need to present the thumbnail in a popup.

**Comment by mcosmin222** [comment] 2018-03-14 19:55
```
 private void Slider_PointerMoved(object sender, PointerRoutedEventArgs e)
        {
            var slider = sender as Slider;
            var length = slider.ActualWidth;
            
            var maximum = slider.Maximum;
            var step = length / maximum;
            
            var hoverPosition = e.GetCurrentPoint(progressSlider).Position.X;
            var estimatedValue = hoverPosition / step;
            System.Diagnostics.Debug.WriteLine(e.GetCurrentPoint(progressSlider).Position.X+ $" est {estimatedValue} Max {maximum}");
        }
```

**Comment by lukasf** [comment] 2018-03-14 20:03
I am surprised to get to know about this ThumbnailRequested event, it sounds interesting at first look. But I am still not sure how exactly this is supposed to work. The event args do not even contain the request position. This does not look like it was thought through. I would not put my bets on this. Have you actually tried this? Is the event fired when hovering the seek bar?

About binary seek, no this is not going to work. The bitrate in video files is very unstable, like, one scene uses a whole lot of bandwidth, then comes a scene with very little motion and bandwidth. It is very unlikely that a binary position matches the same percentual time position in the video. Your users would be very unhappy if they find a scene via seek preview and then the click takes them to a very different point in the file. No this is not going to work, that is why I said, it is not useful for seek preview. It is also not going to be a lot faster. It is only a smaller optimization for cases where you really do not care about the position of a image, such as showing a thumbnail of a video in a file browser. Then it will probably save you a bit of IO and file seeks, and it should be more robust with broken files.

**Comment by mcosmin222** [comment] 2018-03-14 20:07
@lukasf , the thumbnail request even never fires. tried mouse over, tried explicit seek, tried hovering.
It looks like an incomplete API to me...

**Comment by lukasf** [comment] 2018-03-14 20:15
I just tried it and got it fired. Like the docs say, it only works with MediaPlayerElement, not with MediaElement. And it only fires once after you clicked on the seek bar. It is probably intended for streaming scenarios, so you can show a (full screen) preview image while the actual video is being downloaded/buffered after a seek operation. It cannot be used for seek preview.

**Comment by mcosmin222** [comment] 2018-03-14 20:31
I still can't get mine to fire. Regardless. 
I managed to get a dumb preview to work, but it is in need of huge optimizations. These are technicalities of the foreground app, but basically I used an image overlay in my custom media transport controls and the formula above. It works, technically. I ended up in a RPC server exception, probably because I open and close the file at each hover (too lazy to reuse the object).

**Comment by lukasf** [comment] 2018-03-14 20:40
Well, it is a bit different. I tried feeding some random images in ThumbnailRequested, to check what it does. It does actually show the images in a small frame above the seek bar, much like we want it to. But it does so only while actively seeking (cursor pressed). So at the same time, the real video is seeked to the position as well. This does not really make sense. There are also no properties to control seek behavior. It would make sense if we could enable some kind of "deferred seeking", where actual video is only seeked when releasing the mouse button. Then this kind of preview would make sense. But there is no way to change the seek behavior. Obviously, this has not been thought through. Much like the missing seek position parameter. Looks like we'll have to do it ourselves.

@mcosmin222 This will be impossible to get right without proper throttling and reuse of the frame grabber. At least, you have to make sure you only grab one image at a time.

**Comment by mcosmin222** [comment] 2018-03-14 20:59
Ahh now I get it. I **am** using a custom seek behavior, hence why it doesn't fire for me. To implement custom seeking, just replace the existing seek slider with a your own custom slider, then attach event handlers like so:


 progressSlider.AddHandler(Slider.PointerPressedEvent, new PointerEventHandler(PointerPressedEventer), true);
progressSlider.AddHandler(Slider.PointerReleasedEvent, new PointerEventHandler(PointerReleasedEventer), true);

**Comment by touseefbsb** [comment] 2018-03-14 22:36
@lukasf  not sure if this is helpful but we do have a getDeferal method which Returns a deferral that can be used to defer the completion of the ThumbnailRequested event while the thumbnail is generated.

and it is within the args of ThumbnailRequested event

https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.mediatransportcontrolsthumbnailrequestedeventargs#methods_

**Comment by mcosmin222** [comment] 2018-03-15 06:51
That deferal is used to prevent issues caused by early returns from async calls.


As I said, you can implement this with custom media transport controls. I am pretty close to doing it properly

**Comment by lukasf** [comment] 2018-03-15 08:50
@touseefbsb Yeah I do know what a deferral is, it is used everywhere in UWP.

**Comment by touseefbsb** [comment] 2018-03-15 09:43
@mcosmin222  I would really appreciate if you can share the basic implementation, I have worked a lot with custom media transport controls, so I do know how to do that. but I don't have any experience with deferals, so dont really know how that is supposed to work in this scenario.

**Comment by touseefbsb** [comment] 2018-03-15 09:46
also why do you need a custom slider? within custom media transport controls you can just get the slider with GetTemplateChild and attach the events like u said before. what different are we adding on the xaml part for the custom slider, as compared to the default slider already being used in transport controls?

**Comment by mcosmin222** [comment] 2018-03-15 09:52
Because the base media transport controls will handle the input if you use the existing slider, hence why you need to replace it with yours if you want to override the default implementations. 

Deferals have nothing to do with this, as I said, they are used to prevent early returns in async void calls.

**Comment by mcosmin222** [comment] 2018-03-15 10:01
Yes.

**Comment by touseefbsb** [comment] 2018-03-15 10:03
@lukasf  Have u pushed the changes u made yesterday regarding the binary seek, because I cant see the commit.

**Comment by mcosmin222** [comment] 2018-03-15 10:05
He has.

**Comment by touseefbsb** [comment] 2018-03-15 10:16
within the master branch? because I cant see any commits, the latest commit I see is the SDK  update commit by him done yesterday.

**Comment by touseefbsb** [comment] 2018-03-15 10:30
nevermind I found it in framegrabber-opt branch :)

**Comment by mcosmin222** [comment] 2018-03-15 17:12
Well, I did it. I managed to show the seek preview thumbnail in an image on mouse over without triggering the RPC exception (kind of easy to do so if I reuse the stream). My i7 goes through it np, but this feature needs a little more optimization than simply throwing images at it, although the GC should probably handle the memory consumption.

**Comment by touseefbsb** [comment] 2018-03-15 17:16
@mcosmin222  great work I hope I can start attempting to do it as well once I am able to build the repo lol

**Comment by touseefbsb** [comment] 2018-03-16 10:45
@mcosmin222  are you using pointermoved event on slider or pointer pressed and pointer released events?

**Comment by mcosmin222** [comment] 2018-03-16 11:56
The event is pointer moved. I described above how to convert pointer position to frame position.

**Comment by touseefbsb** [comment] 2018-03-16 12:02
@mcosmin222  the forumula u gave above is **estimatedValue** that frame position ?

**Comment by touseefbsb** [comment] 2018-03-16 15:29
the estimatedValue seems to be in **double** while we have to provide the **position**to the getframe method as **TimeSpan** or can we provide estimatedValue as **long ticks** to get a timespan object? @mcosmin222

**Comment by lukasf** [comment] 2018-03-16 15:38
Since this is a custom seek bar, you will have to decide yourself how you map the duration to seek bar position. Either you make seekbar values 0.0 to 1.0, then you have to multiply the value by duration. Or you make the seekbar maximum = duration.TotalSeconds. It is your choice. You need to manage it completely, including seeking, seek preview, updating position during playback...

**Comment by mcosmin222** [comment] 2018-03-16 16:22
Duration.TotalSeconds is the easiest choice.

**Comment by touseefbsb** [comment] 2018-03-16 16:51
@mcosmin222  so whenever we play a video we have to set the maximum of the custom slider to the duration.totalSeconds of the video file? which we can get from **MediaPlayerElement.MediaPlayer.PlaybackSession.Position**?
 and then we have to register to the value changed event of the slider, and set the changed value to the position of the video, so that use can control the position with the slider and vice versa?

**Comment by lukasf** [comment] 2018-03-16 17:22
Correct.

**Comment by lukasf** [comment] 2018-04-16 20:47
Closing this.

**Closed by lukasf** 2018-04-16 20:47 UTC
