### ISSUE TITLE
External subtitle won't use providers

### ISSUE THREAD

**Issue by pashmak73** [lukasf/FFmpegInterop#90] opened 2019-02-20 22:01 UTC
Hi,
After you guys said to me in #88 , I decided to test this by myself.
I use master branch.
1. It seems applying styles won't affect anything.
```C#
Config = new FFmpegInteropConfig();
Config.AutoSelectForcedSubtitles = true;
Config.OverrideSubtitleStyles = true;
Config.SubtitleStyle = new TimedTextStyle() { Background = Colors.Cyan };
// create mss and play code
```

2. Also it seems built-in subtitle isn't working well.
when you try to select built-in subtitle, app will crash without any error:
![image](https://user-images.githubusercontent.com/46992431/53127240-3f3f3c80-3577-11e9-8137-3ff6491438ab.png)
This won't happen, if you choose an external subtitle and after that if you select built-in subtitle app won't crash but still can't see built-in subtitle on the screen.

3. I'm sure that external subtitle won't parse by SubtitleProvider you've added. because I changed the color, text inside [SubtitleProviderSsaAss](https://github.com/lukasf/FFmpegInterop/blob/master/FFmpegInterop/SubtitleProviderSsaAss.h) (for testing purpose) but doesn't effect anything!
It seems MediaElement will take care of it.

Should I test with #79 too?

Note: I tested with minimum target platform 14393 and 15063.

**Comment by pashmak73** [comment] 2019-02-20 22:32
I tested #79 too.
here: this is the difference between WIN API and your subtitle provider for ssa subs:
![image](https://user-images.githubusercontent.com/46992431/53129331-84b23880-357c-11e9-8f14-f1f5a26ee2f3.png)

1. WIN API (correct subtitle position)
2. FFmpeg

I'm gonna test more.

**Comment by mcosmin222** [comment] 2019-02-21 07:37
Ofc, the work on external subs is not merged yet. Try the external_subtitle_parsers branch. It comtaind external subtitles support, plus additional fixes for internal ones.

**Comment by lukasf** [comment] 2019-02-21 08:11
Let's clarify a few things:

1. External subs on master branch don't go through our lib. So style overrides won't have any effects. Use branch from #79 for that.
2. Creating a style that has all the mandatory parameters set to values compatible with UWP is tricky. If you want to override the style, I recommend you use the default style that is already set in the config class, and modify selected properties from that. The crash you saw might be a result of incomplete style definition.
3. SSA Subtitle parsing is not 100% complete. We parse some things but not everything. If you want to help improve the code, your help is appreciated. For example, we do respect styles that are explicitly defined in the style header region. But if colors, effects or positions are set inline, using tag code inside the actual sub line, these are currently ignored. The format is pretty fancy, respecting all the options is a lot of work. And some of the fancy effects (like animations, color changes) are impossible to realize using our current approach.
4. Theoretically it would also be possible to use FFmpeg and libssa to actually render the ssa sub perfectly (with original libssa code form the creators of SSA format) into the video image. But that also has some downsides. Performance would be degraded. Resolution would be limited to video resolution, so text would not be sharp on high res displays. Style overrides would be hard to integrate. Plus, it would probably be a whole lot of work, which I currently don't plan to do. Just saying.

**Comment by pashmak73** [comment] 2019-02-21 11:03
As a test purpose, I've added supports for italic and underline for ssa subtitle, but it seems something is wrong and it doesn't work.
here is my code:
```c++
virtual IMediaCue^ CreateCue(AVPacket* packet, TimeSpan* position, TimeSpan *duration) override
{
	AVSubtitle subtitle;
	int gotSubtitle = 0;
	auto result = avcodec_decode_subtitle2(m_pAvCodecCtx, &subtitle, &gotSubtitle, packet);
	if (result > 0 && gotSubtitle && subtitle.num_rects > 0)
	{
		auto str = utf8_to_wstring(std::string(subtitle.rects[0]->ass));
				
		int startStyle = -1;
		int endStyle = -1;
		int lastComma = -1;
		bool hasError = false;
		for (int i = 0; i < textIndex; i++)
		{
			auto nextComma = str.find(',', lastComma + 1);
			if (nextComma != str.npos)
			{
				if (i == styleIndex)
				{
					startStyle = (int)nextComma + 1;
				}
				else if (i == styleIndex + 1)
				{
					endStyle = (int)nextComma;
				}
				lastComma = (int)nextComma;
			}
			else
			{
				// this should not happen. still we try to be graceful. let's use what we found.
				hasError = true;
				break;
			}
		}

		SsaStyleDefinition^ style = nullptr;
		if (!hasError && startStyle > 0 && endStyle > 0)
		{
			auto styleName = convertFromString(str.substr(startStyle, endStyle - startStyle));
			if (styles.find(styleName) != styles.end())
			{
				style = styles[styleName];
			}
		}

		if (lastComma > 0 && lastComma < (int)str.length() - 1)
		{
			// get actual text
			str = str.substr(lastComma + 1);

			find_and_replace(str, L"\\N", L"\n");
			str.erase(str.find_last_not_of(L" \n\r") + 1);

			// strip effects from string
			// TODO we could parse effect and use at least bold and italic
			auto underline = false;
			auto italic = false;
			while (true)
			{
				auto nextEffect = str.find('{');
				if (nextEffect != str.npos)
				{
					auto endEffect = str.find('}', nextEffect);
					if (endEffect != str.npos)
					{
						if (endEffect < str.length() - 1)
						{
							auto effect = str;

							try
							{
								if (effect.find(L'\\u') != effect.npos)
								{
									underline = true;
								}
								if (effect.find(L'\\i') != effect.npos)
								{
									italic = true;
								}
							}
							catch (...) {}
							str = str.substr(0, nextEffect).append(str.substr(endEffect + 1));
						}
						else
						{
							str = str.substr(0, nextEffect);
						}
					}
					else
					{
						break;
					}
				}
				else
				{
					break;
				}
			}

					
			auto timedText = convertFromString(str);
			if (timedText->Length() > 0)
			{
				TimedTextCue^ cue = ref new TimedTextCue();
				if (!m_config->OverrideSubtitleStyles && style)
				{
					cue->CueRegion = style->Region;
					cue->CueStyle = style->Style;
				}
				else
				{
					cue->CueRegion = m_config->SubtitleRegion;
					cue->CueStyle = m_config->SubtitleStyle;
				}
						
				cue->CueStyle->IsUnderlineEnabled = underline;
				//cue->CueStyle->IsUnderlineEnabled = true;

				cue->CueStyle->FontStyle = italic ? TimedTextFontStyle::Italic : TimedTextFontStyle::Normal;
				TimedTextLine^ textLine = ref new TimedTextLine();
				textLine->Text = timedText + "\nitalic: " + italic + "\nunderline: " + underline;
				cue->Lines->Append(textLine);

				return cue;
			}
		}
	}
	else if (result <= 0)
	{
		OutputDebugString(L"Failed to decode subtitle.");
	}

	return nullptr;
}
```
subtitle text: `{\pos(188.8,53.6)\fad(1000,1000)\u1}ترجمه و زیرنویس`
and screenshot:
![image](https://user-images.githubusercontent.com/46992431/53164401-59afff00-35e5-11e9-80dc-681084493657.png)
as you can see, both italic and underline are TRUE, but it doesn't change anything in the text.
where am I doing wrong?

**Comment by pashmak73** [comment] 2019-02-21 13:09
I have another question:
Is it possible to render que from C#? because I've already have an subtitle parser in C# and it's very fast:
```
[Sub rip]		Reading 5223 subtitle in 00:00:03.4243775	[from 211681 lines]
[Micro dvd]		Reading 5223 subtitle in 00:00:01.6949466	[from 52231 lines]
[Universal sub]		Reading 5223 subtitle in 00:00:03.3685965	[from 156714 lines]
[Sub viewer 2.0]	Reading 5223 subtitle in 00:00:01.1394282	[from 156701 lines]
[Dvd subtitle]		Reading 5223 subtitle in 00:00:01.4983813	[from 316154 lines]
```

**Comment by mcosmin222** [comment] 2019-02-21 14:57
Ours will be faster :).

Yeah, you can create a Timedmetadatatrack, create the timedtextcues and then add the track to our playback item. The same way we do.

**Comment by pashmak73** [comment] 2019-02-21 15:01
> As a test purpose, I've added supports for italic and underline for ssa subtitle, but it seems something is wrong and it doesn't work.
> here is my code:
> 
> ```c++
> virtual IMediaCue^ CreateCue(AVPacket* packet, TimeSpan* position, TimeSpan *duration) override
> {
> 	AVSubtitle subtitle;
> 	int gotSubtitle = 0;
> 	auto result = avcodec_decode_subtitle2(m_pAvCodecCtx, &subtitle, &gotSubtitle, packet);
> 	if (result > 0 && gotSubtitle && subtitle.num_rects > 0)
> 	{
> 		auto str = utf8_to_wstring(std::string(subtitle.rects[0]->ass));
> 				
> 		int startStyle = -1;
> 		int endStyle = -1;
> 		int lastComma = -1;
> 		bool hasError = false;
> 		for (int i = 0; i < textIndex; i++)
> 		{
> 			auto nextComma = str.find(',', lastComma + 1);
> 			if (nextComma != str.npos)
> 			{
> 				if (i == styleIndex)
> 				{
> 					startStyle = (int)nextComma + 1;
> 				}
> 				else if (i == styleIndex + 1)
> 				{
> 					endStyle = (int)nextComma;
> 				}
> 				lastComma = (int)nextComma;
> 			}
> 			else
> 			{
> 				// this should not happen. still we try to be graceful. let's use what we found.
> 				hasError = true;
> 				break;
> 			}
> 		}
> 
> 		SsaStyleDefinition^ style = nullptr;
> 		if (!hasError && startStyle > 0 && endStyle > 0)
> 		{
> 			auto styleName = convertFromString(str.substr(startStyle, endStyle - startStyle));
> 			if (styles.find(styleName) != styles.end())
> 			{
> 				style = styles[styleName];
> 			}
> 		}
> 
> 		if (lastComma > 0 && lastComma < (int)str.length() - 1)
> 		{
> 			// get actual text
> 			str = str.substr(lastComma + 1);
> 
> 			find_and_replace(str, L"\\N", L"\n");
> 			str.erase(str.find_last_not_of(L" \n\r") + 1);
> 
> 			// strip effects from string
> 			// TODO we could parse effect and use at least bold and italic
> 			auto underline = false;
> 			auto italic = false;
> 			while (true)
> 			{
> 				auto nextEffect = str.find('{');
> 				if (nextEffect != str.npos)
> 				{
> 					auto endEffect = str.find('}', nextEffect);
> 					if (endEffect != str.npos)
> 					{
> 						if (endEffect < str.length() - 1)
> 						{
> 							auto effect = str;
> 
> 							try
> 							{
> 								if (effect.find('\\u') != effect.npos)
> 								{
> 									underline = true;
> 								}
> 								if (effect.find('\\i') != effect.npos)
> 								{
> 									italic = true;
> 								}
> 							}
> 							catch (...) {}
> 							str = str.substr(0, nextEffect).append(str.substr(endEffect + 1));
> 						}
> 						else
> 						{
> 							str = str.substr(0, nextEffect);
> 						}
> 					}
> 					else
> 					{
> 						break;
> 					}
> 				}
> 				else
> 				{
> 					break;
> 				}
> 			}
> 
> 					
> 			auto timedText = convertFromString(str);
> 			if (timedText->Length() > 0)
> 			{
> 				TimedTextCue^ cue = ref new TimedTextCue();
> 				if (!m_config->OverrideSubtitleStyles && style)
> 				{
> 					cue->CueRegion = style->Region;
> 					cue->CueStyle = style->Style;
> 				}
> 				else
> 				{
> 					cue->CueRegion = m_config->SubtitleRegion;
> 					cue->CueStyle = m_config->SubtitleStyle;
> 				}
> 						
> 				cue->CueStyle->IsUnderlineEnabled = underline;
> 				//cue->CueStyle->IsUnderlineEnabled = true;
> 
> 				cue->CueStyle->FontStyle = italic ? TimedTextFontStyle::Italic : TimedTextFontStyle::Normal;
> 				TimedTextLine^ textLine = ref new TimedTextLine();
> 				textLine->Text = timedText + "\nitalic: " + italic + "\nunderline: " + underline;
> 				cue->Lines->Append(textLine);
> 
> 				return cue;
> 			}
> 		}
> 	}
> 	else if (result <= 0)
> 	{
> 		OutputDebugString(L"Failed to decode subtitle.");
> 	}
> 
> 	return nullptr;
> }
> ```
> 
> subtitle text: `{\pos(188.8,53.6)\fad(1000,1000)\u1}ترجمه و زیرنویس`
> and screenshot:
> ![image](https://user-images.githubusercontent.com/46992431/53164866-7dc01000-35e6-11e9-8299-48f6656d87c4.png)
> 
> as you can see, underline is TRUE, but it doesn't change anything in the text.
> where am I doing wrong?

What about this one, what is the problem?

**Comment by mcosmin222** [comment] 2019-02-21 16:15
Could be that you set the properties after asigning the style to the cue.

**Comment by lukasf** [comment] 2019-02-21 16:29
I think the problem is that you use the exact same style instance for all cues. So when the italic cue comes, the style instance is changed from normal to italic. Now when the next cue is parsed, it might reset the italic flac. Instead of modifying the style instance, you need to create a new instance, copy all the properties over, then change the italic flag on the style copy, and use the style copy only for this one cue.

I tested by setting underline and italic in the default style, and it works properly.

**Closed** 2019-02-26 00:31 UTC

**Comment by lukasf** [comment] 2019-02-26 09:55
If you have a working solution, it would be nice if you can do a PR.

**Comment by pashmak73** [comment] 2019-03-01 05:05
@lukasf sorry I wasn't home.
Unfortunately couldn't fix it in C++. but I wrote a tiny ssa parser with C#, works good:
![image](https://user-images.githubusercontent.com/46992431/53617410-55df3680-3bfc-11e9-8513-fcce535e8038.png)
![image](https://user-images.githubusercontent.com/46992431/53616721-34c91680-3bf9-11e9-919f-deb8238c9fa9.png)
![image](https://user-images.githubusercontent.com/46992431/53616748-50342180-3bf9-11e9-8230-4cead3483478.png)
![image](https://user-images.githubusercontent.com/46992431/53617260-b02bc780-3bfb-11e9-90d6-5fb3bbdc0abe.png)

As you can see, styles and effects works perfectly (except positions).
Here: [SsaParser.zip](https://github.com/ffmpeginteropx/FFmpegInteropX/files/2917968/SsaParser.zip)

I can create a separate project for FFmpegInterop subtitle parser with C# (if you want) and work together on this project as an Helper project.

**Comment by lukasf** [comment] 2019-03-01 10:49
Hi @pashmak73, thank you, I think an external C# project is not an option for us when the same can be done in C++ as well. When doing it inside our lib, it would work for both external and embedded subtitles, and would allow effects to work not only for SSA but also other formats (ffmpeg translates all other text subtitle formats into ssa).
