### ISSUE TITLE
Problem with seek

### ISSUE THREAD

**Issue by ramtinak** [lukasf/FFmpegInterop#7] opened 2018-02-15 09:51 UTC
Hi,
I just find when you trying to seek a video, audio is fine but video will slow playing.
This issue will appear only when you trying to seek.
Slowly video only VP9 codec id, even when plays 720p videos.
I tested with this video:
http://dl.subrica.download/musicvideos/Era%20Istrefi/Era%20Istrefi%20-%20Bonbon%20(720)(subrica).mkv

**Comment by lukasf** [comment] 2018-02-15 13:29
Hi, thank you for reporting. I will check the file and report back.

**Comment by lukasf** [comment] 2018-02-16 12:35
I cannot reproduce the problem. I can happily seek around the file and playback is smooth and fast. CPU usage is very low at 3-4% only. What device are you using for playback?

**Comment by ramtinak** [comment] 2018-02-16 19:35
In the last post I said slow! I was wrong! when I seek the video, video is not sync with audio!!!!

I find something else! sometimes when I tried to seek, there is no audio!

---
I tested in my PC.

I used your hevc passthrough branch(you mentioned before) in my app and it can play this video smoothly.
But with your new ffmpeginterop as I said there's a problem.

**Comment by lukasf** [comment] 2018-02-17 12:49
I cannot reproduce sync problems here. In the beginning I thought it is out of sync as well, but it was only due to the content: E.g. at position 35s she continues singing in the music, but in the video she does not sing. Later she continues in the video as well. When seeking there it looks like video is out of sync, but it is just how the video is. I observed the same with other players or when playing from start without seeking. There was at least one other part later where video and audio look a bit out of sync. The video is just not done very well, or maybe it was even done so on purpose, who knows.

I also never had no audio on seek...

Did you build ffmpeg from the sources that come with the FFmpegInterop library? If you use different sources or precompiled binaries form some other website, then you might run into problems.

**Comment by ramtinak** [comment] 2018-02-17 13:28
If you remember, I used your hevc passthrough branch in the ms master branch,(both audio and video decoding is true) in this version there's no issue. and after seeking video and audio is just fine.

I also tested this video in these players, "PotPlayer, KMPlayer and Movies and TV" and none of these has this issue. 

No I did not, because there's some error (I really don't remember). I used nuget package manager, search for Ffmpeg.win10, I know It's old, but I cannot figure it out the errors from compiling binaries.

If you have latest ffmpeg libs form x86,x64 and arm, please upload them. It's really be helpful,
Thanks

**Comment by lukasf** [comment] 2018-02-17 19:34
While I still cannot reproduce the problem, I have created the branch "seek-issue" for you to try. I remembered one piece of code where I think seeking could cause problems, if a stream does not correctly report timestamps. For me, the file does report correct timestamps, but it could be that your ffmpeg version behavevs differently. Please test with the branch an check if the problem occurs there, too. There is even one other thing I could try if it does not help.

Have you also retested with the hevc branch, to verify that the problem still does not occur there?

**Comment by lukasf** [comment] 2018-02-17 19:36
Ah and one more question: Will the video catch up after a while, or is it out-of-sync until end of file?

**Comment by ramtinak** [comment] 2018-02-17 20:40
I tested seek-issue branch. It's OK, everything works well. 
and it's has fast seeking! very good! Looks fine to me.

I don't need to test Hevc branch! because already is in my player! and works well.

and about your last question, I know it's no need to answer this because problem was solved, but:
video never catch up, in some position, audio stops(will ends!) but video is still playing.

Thanks

**Comment by lukasf** [comment] 2018-02-17 21:45
Cool, good to hear that! I think the problem originally comes because you use an older ffmpeg build than us. That nuget packet has version 3.1.3, we are using 3.3.2. But there was also a problem in the code which seems to be solved now. If the video never catches up, then it is really the problem which I assumed, it also makes sense that at some positions no audio comes. 

Still, I'd recommend you to use version 3.3 ffmpeg binaries. I will try to up them somewhere for you tomorrow.

**Comment by lukasf** [comment] 2018-02-18 15:47
Can you please re-test with the latest version of the seek-issue stream? I have merged master changes and done one additional small change.

When it works, you can try to switch to ffmpeg 3.3.2:

https://1drv.ms/u/s!Asy3bMoFN_qNh70aBbiEta_CK_O8cg

**Comment by ramtinak** [comment] 2018-02-18 16:30
I tested again, there wasn't a problem with that and everything works very well.
Both with ffmpeg 3.1.3 and 3.3.2 are just fine.

by the way, thanks for uploading ffmpeg libs.

**Comment by lukasf** [comment] 2018-02-18 20:08
Alright, PR is merged into master branch, closing this...

**Closed by lukasf** 2018-02-18 20:08 UTC
