### ISSUE TITLE
dispatch exception in ffmpeginterop.dll

### ISSUE THREAD

**Issue by touseefbsb** [lukasf/FFmpegInterop#50] opened 2018-05-29 21:20 UTC
I just went to crashes of my app and noticed this new kind of crash coming from ffmpeginterop.dll

>fail_fast_invalid_arg_c0000409_ffmpeginterop.dll!guard_dispatch_icall_nop

 attached is the stacktrace file I downloaded from dev center.  
[stackTrace (1).zip](https://github.com/lukasf/FFmpegInterop/files/2051053/stackTrace.1.zip)

**Comment by mcosmin222** [comment] 2018-05-30 08:06
guard_dispatch_icall_nop is a threading error. (everything that has the word dispatch in it is about multithreading in windows).

I do not believe this is caused by ffmpeg interop itself (which is pretty thread safe inside), if it were it would have been pretty obvious as the library would not work properly for any of us.

So it is likely something that you do in your app. Do you call ffmpeg interop on background threads? perhaps to fetch video frames?

Or perhaps you modify your MediaElement on the wrong thread?

**Comment by touseefbsb** [comment] 2018-05-30 19:45
@mcosmin222  if by custom selectors you mean custom media playback list then yes I am using my own made media playbacklist as you suggested to keep memory efficient. and when new media track is requested I create new mediaplaybackitem on demand ( like lazy loading ) and then assign that to mediasource. I am not touching the media tracks in my app, the timemetadatatracks are for subs and I have not implemented custom stuff for subs yet, everything in that perspective is being done by default by the library and mediaplayerelement. the only custom thing I am doing here is custom media playbacklist, and I wonder how can I test it? because it is working ok on my machine, even when I change the videos in my playlist.

**Comment by mcosmin222** [comment] 2018-05-31 07:18
Are you sure about that? I see you are also using custom media transport controls.
The funny part about threading errors is that they are pretty hard to reproduce.

**Comment by touseefbsb** [comment] 2018-05-31 10:32
yes that is the problemabt threading it is a disgrace to programming :P I hope to shift to reactive programming using reactive UI library, maybe then all these problems can go away. btw u have my app installed? I mean how do you know I am using custom media transport controls?

**Comment by mcosmin222** [comment] 2018-05-31 11:19
The problems will not go away because this isn't a problem at the UI level.
Yes, I have your app installed and that is how I know you use custom media transport controls :P

**Comment by touseefbsb** [comment] 2018-05-31 11:34
well this is very disapointing , if I dnt know wht the problem is how can I solve it lol

**Comment by mcosmin222** [comment] 2018-05-31 12:00
You have a clue about what the problem might be, so you can start and see where threading conflicts might occur.

Remember that all events raised by MediaPlayer, MediaElement, MediaSource ,MediaStreamSource and related objects fire each on a different thread*. Try to see where one thread might interact with another, see the order in which the events fire, and what code executes in close time frames. 

* as far as you care. They actually fire in different threading contexts, the actual OS thread to execute said events in their specific contexts might not be different, but that is just an implementation detail of the threadpool that you do not care about.

**Comment by touseefbsb** [comment] 2018-05-31 18:31
@mcosmin222  thanks for the help, I'll try to solve it :)

**Comment by mcosmin222** [comment] 2018-06-03 14:20
Closing this. See #52

**Closed by mcosmin222** 2018-06-03 14:20 UTC
