### ISSUE TITLE
readstream is not being disposed in the sample, why is that

### ISSUE THREAD

**Issue by touseefbsb** [lukasf/FFmpegInterop#36] opened 2018-04-19 08:30 UTC
IRandomAccessStream readStream = await file.OpenAsync(FileAccessMode.Read);

I just noticed within sample we create a read stream from StorageFile in order to assign it to use it for MediSource, but it is a disposable object so I wonder why it isn't being disposed? is it because disposing it will cancel the media being played?

And another question : I see that "var source = FFmpegMSS.CreateMediaPlaybackItem();" is giving us  a MediaPlaybackItem, which can only be used with Mediaplayerelement, how is the sample app setting it to the MediaElement? is it a custom type which is also named as MediaPlaybackItem? ( but not the native one ? )

**Comment by mcosmin222** [comment] 2018-04-19 09:02
Hmmm. The stream should be disposed in the destructor of the interop object.

**Comment by mcosmin222** [comment] 2018-04-19 10:07
I checked. The stream is correctly released in the dctor. The MediaPlaybackItem is the native type. It works with mediaelement too.

**Comment by lukasf** [comment] 2018-04-19 10:16
The stream must be kept open as long as the media is playing, otherwise any read attempt would fail. The stream is released when FFmpegInteropMSS is released/collected.

**Comment by touseefbsb** [comment] 2018-04-19 10:42
in my app I am using  mediaPlaybacklist as my primary source to the "mediaPlayer" object, which is ultimately set to the mediaplayerelement ( with setmediaplayer() ) .
so I am creating multiple mediaplaybackitems, and adding them to my mediaplaybacklist. right now I am creating the source directly from storagefiles and setting them to my mediaplaybackitems.

if I use this library can I keep doing it the same way ? or do I need to worry about the streams being in memory ? I mean is it the same if I use the native way or the dispose mechanism in this library is only suited for a single stream loaded or running at a time ?


Also I noticed that in "CreateMediaPlaybackItem" method I library, the audiotracks and subs stuff is also being initialized. so do I need to use that method in order to get the subs and audio tracks feature? or can I simply create mediaSource only from the library and then create my own MediaPlaybackItem?

**Comment by mcosmin222** [comment] 2018-04-19 11:09
MediaPlaybackList is just a glorified List<MediaPlaybackItem>. In my app i dont use it because of the amount of time it takes to create the media stream sources and the memory it would use. 

I just open them 1 by 1 when the time comes, and keep the next item also opened to simulate gapless playback. But this is up to you how to use it.

**Comment by touseefbsb** [comment] 2018-04-19 11:57
@mcosmin222  so I wonder why do we have a CreateMediaPlaybackItem method? I mean yes we can surely have a helper method to reduce the code for developer, but the stuff happening regarding audio tracks and subtitle initialization, that stuff confused me, so I am wondering because apart from that, this method just creates a MediaPlaybackItem like I am normally doing in my app. but wht difference does that ( subs and audio tracks initialization ) make and why is it there?

**Comment by touseefbsb** [comment] 2018-04-19 12:10
btw mediaplaybacklist has a property something like :"maxitemstokeepopen"  which can be set to tell the list how many items should remain opened for seemless playback, and default value of this is 3, I think this is exactly wht u r doing in ur implementation.

**Comment by lukasf** [comment] 2018-04-19 12:56
If you want subtitle support and correct names for your audio streams, then you must use CreateMediaPlaybackItem. If you use GetMediaStreamSource, you won't have any subs. Maybe we should even deprecate that old GetMediaStreamSource, so people do not use it accidentially.

When you create MediaPlaybackItems normally from IRandomAccessStream, there is not so much overhead for the creation. The file will only be read short before playback, and only 3 items will be kept open by default (originally, all files were kept open once played, the item limit was only added later). So for normal playback, using MediaPlaybackItems in a MediaPlaybackList is not problematic from resource perspective. But you cannot create a MediaStreamSource without parsing the file. So if you want to use FFmpegInterop, creating a MediaPlaybackItem from a file through the lib will require more resources and memory, compared to normal creation of MediaPlaybackItem. It might be the better strategy to only create them on demand, like @mcosmin222 does. For audio files, MediaPlaybackList has the benefit of gapless playback. But for video files, that is not really important, so using your own list internally is usually the better way.

**Comment by mcosmin222** [comment] 2018-04-19 12:57
CreateMediaPlaybackItem  is a helper method which gives you a fully initialized MediaPlaybackItem, which contains all the TimedMetadataTracks we resolved from internal subtitles. If we didn't expose this method, each consumer of our library would have to do this by themselves, and this could cause bugs which would ultimately end up and issues here. This way, we give the consumers a fully tested and working method to create the MediaPlaybackItem.

However, the MediaPlaybackItem is not suitable for all the tasks a MediaStreamSource can accomplish, top among these being transcoding. So you can still get to the MediaStreamSource without a MediaPlaybackItem for those topics.

**Conclusions:**

For the average playback app, use **CreateMediaPlaybackItem**.
For transcoding and more advanced scenarios, use the **MediaStreamSource** directly.

**Comment by touseefbsb** [comment] 2018-04-19 13:27
@lukasf  ther overhead caused by CreateMediaPlaybackItem() of this library, is because of "subs initialization" or because of the fact that MediaSouce is being initialized with "Stream" and not directly from a "StorageFile"? bcz normally ( not using this lib )  a MediaPlaybackItem can be directly initialized from a StorageFile without involving the stream.

**Comment by mcosmin222** [comment] 2018-04-19 13:34
The overhead is caused by our read actions needed to determine the codec and its configuration (subs included, but this isn't the only thing). You can step through the code and see what we do.  

All MediaPlaybackItems eventually go through a Stream, the StorageFile overload is just a helper. You can't read a file without opening a Stream first.

**Comment by touseefbsb** [comment] 2018-04-19 13:37
so basically what you guyx are suggesting is , instead of using "MediaPlaybackList" I can use my custom implementation where I can maintain a List<StorageFile>  and on demand, I can call method "CreateMediaPlaybackItem(onDemandFile)" and get the required MediaPlaybackItem and then assign that item a source of my "mediaPlayer". and lets say I keep open only 3 items at a time, so how do I dispose or close the un needed items? I mean the items (mediaPlaybackItems ) which  out of range to keep open, how do I release their resources, do I assign those items to null? or call Source.Dispose() ? Also keeping the Storage Files in the list won't cause any extra resources as compared to normal "mediaPlaybackList" because even if we keep 3 items open, we do need StorageFiles for all of them ( so that they can get us their respective mediaPlaybackItems on demand anytime ) ?

**Comment by touseefbsb** [comment] 2018-04-19 13:38
@mcosmin222  by transcoding u mean video file conversions and other stuff like that?

**Comment by mcosmin222** [comment] 2018-04-19 13:41
> so basically what you guyx are suggesting is , instead of using "MediaPlaybackList" I can use my custom implementation where I can maintain a List and on demand, I can call method "CreateMediaPlaybackItem(onDemandFile)" and get the required MediaPlaybackItem and then assign that item a source of my "mediaPlayer". and lets say I keep open only 3 items at a time, so how do I dispose or close the un needed items? I mean the items (mediaPlaybackItems ) which out of range to keep open, how do I release their resources, do I assign those items to null? or call Source.Dispose() ? Also keeping the Storage Files in the list won't cause any extra resources as compared to normal "mediaPlaybackList" because even if we keep 3 items open, we do need StorageFiles for all of them ( so that they can get us their respective mediaPlaybackItems on demand anytime ) ?

MediaPlaybackItem is IDisposable, simply call its Dispose method to release its resources.

> @mcosmin222 by transcoding u mean video file conversions and other stuff like that?

Yes, audio & video conversion.

**Comment by touseefbsb** [comment] 2018-04-19 13:44
thanks for all the clarification guyx , really appreciated :)

**Closed** 2018-04-20 20:48 UTC
